import Head from 'next/head'
import Image from 'next/image'
import ProjectCard from '../components/ProjectCard'
import WebsiteBase from '../components/WebsiteBase'
import styles from '../styles/Home.module.css'

function constructProject(id, name, description, url, github_url, skills)
{
  return {id, url, description, name, github_url, skills}
}



/*export default function Home({projects}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <h3>{/*JSON.stringify(data)}</h3>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {projects.map(project => (<ProjectCard {...project} key={project.id}/>))}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <h3>Nothing</h3>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}*/

export default function Home({projects}) {
  return (
    <WebsiteBase>
      <div className={styles.main}>{projects.map(project => (<ProjectCard {...project} key={project.id}/>))}</div>
    </WebsiteBase>
  );
}

//export async function getServerSideProps() { use static props rather than serversideprops
export async function getStaticProps(){ 
  // Fetch data from external API
  //const res = await fetch(`https://api.github.com/users/gerardvee`)
  //const data = await res.json()
  const projects = [
    constructProject(0, 'Delano Farms', 'A Delano farms website',  'https://www.delanofarms.com/', 'github.com/GerardVee/delano_farms', ['react', 'php', 'nodejs', 'javascript']),
    constructProject(1, 'Gighub', 'Github + LinkedIn',  'https://www.gighub.com/', 'github.com/tfwatson/csci201-final-project', ['java', 'java servlets', 'mysql', 'github']),
    constructProject(2, 'Game', 'A game built in js',  'https://www.games.com/', 'github.com/GerardVee/game', ['javascript', 'canvas', 'html', 'css']),
  ];

  // Pass data to the page via props
  return { props: { projects } }
}

